### ISSUE TITLE
Issue with Raycast

### ISSUE THREAD

**Issue by lyraqd** [alanzchen/chatgpt-quick-actions#1]
For some reason, after adding it to Raycast, it keeps telling me "No executable JS file found"...

Reason: No executable JS file found
Domain: commands
Recovery: Build the extension before usage

**Comment by alanzchen** [comment]
Oops, can you try to run:

```
npm install
npm run build
```

If you do not have `nodejs` installed already, try installing it with `brew install node`.
Of course you will need `homebrew` as well: https://brew.sh/

Because I don't have a fresh machine to test this out, please let me know if this is sufficient to make it work!
